In [1]:
import pandas as pd
import numpy as np
import csv

In [20]:
df = pd.read_csv("C:/Users/lylos/github/CCNY_Upskill/IBM_Tools_for_DS/goodreads_library_export.csv")
df.head(5)

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Private Notes,Read Count,Recommended For,Recommended By,Owned Copies,Original Purchase Date,Original Purchase Location,Condition,Condition Description,BCID
0,40594396,The Devil Aspect,Craig Russell,"Russell, Craig",NaN,"=""0385544367""","=""9780385544368""",0,4.02,Doubleday Books,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1,29906980,Lincoln in the Bardo,George Saunders,"Saunders, George",NaN,"=""0812995341""","=""9780812995343""",0,3.75,Random House,...,NaN,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
2,26007349,Big Little Lies,Liane Moriarty,"Moriarty, Liane",Caroline Lee,"=""""","=""9781490627298""",3,4.27,Recorded Books,...,NaN,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3,46041199,"Kim Jiyoung, Born 1982",Cho Nam-Joo,"Nam-Joo, Cho",Jamie Chang,"=""1631496700""","=""9781631496707""",0,4.15,Liveright,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
4,5025780,Beloved,Toni Morrison,"Morrison, Toni",NaN,"=""""","=""""",0,3.86,Vintage,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [21]:
to_drop = [ "Book Id",
           "Author l-f",
           "Additional Authors",
           "ISBN", 
           "ISBN13",
           "Private Notes",
           "Recommended For", 
           "Recommended By",
           "Owned Copies",
           "Original Purchase Date",
           "Original Purchase Location",
           "Condition",
           "Condition Description",
           "BCID", 
           "My Review", 
           "Spoiler"
          ]
df.drop(to_drop, inplace = True, axis = 1)
df.head(5)

,Title,Author,My Rating,Average Rating,Publisher,Binding,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,Read Count
0,The Devil Aspect,Craig Russell,0,4.02,Doubleday Books,Hardcover,414.0,2019.0,2018.0,NaN,2020/08/17,to-read,to-read (#714),to-read,0
1,Lincoln in the Bardo,George Saunders,0,3.75,Random House,Hardcover,343.0,2017.0,2017.0,NaN,2020/03/26,"on-kobo, currently-reading, 2020, listened-to","on-kobo (#118), currently-reading (#3), 2020 (...",currently-reading,1
2,Big Little Lies,Liane Moriarty,3,4.27,Recorded Books,Audiobook,16.0,2014.0,2014.0,2020/08/14,2020/08/09,"listened-to, 2020","listened-to (#43), 2020 (#43)",read,1
3,"Kim Jiyoung, Born 1982",Cho Nam-Joo,0,4.15,Liveright,Hardcover,176.0,2020.0,2016.0,NaN,2020/08/10,to-read,to-read (#713),to-read,0
4,Beloved,Toni Morrison,0,3.86,Vintage,Kindle Edition,291.0,2007.0,1987.0,NaN,2013/09/25,to-read,to-read (#712),to-read,0